#---Title: Generate Sample weights for Visit 1, 2, 3                        ---#
#---       with Weight Components following Add Health procedures           ---#

#---Description: This code will generate weight components per ADD Health   ---#
#---             procedures. The code is based on                           ---#
#---             V3_ah_wc_samp_outline_01.Rmd. The code is recoded such     ---#
#---             that it loops through 1000 samples generated by V3_samp.R  ---#

#---Author: Jose S. Lopez

# Setup
library(tidyverse)
sim_batch <- as.numeric(Sys.getenv("SLURM_ARRAY_TASK_ID"))
n_batch <- 25

sim_start <- (sim_batch-1)*n_batch+1
sim_end <- sim_batch*n_batch

# Remove all data from Global Environment
# rm(list = ls())

# The naming convention for the samples generated are sample_1, sample_2,
# sample_3, . . . , sample_1000.

for(i in seq(from=sim_start, to=sim_end, by=1)){
  sample_01 <- read.csv(paste0("/pine/scr/j/s/jsljr/HCHSSOL_AddHealth_WCs/Original_Samples/sample_",i,".csv"))
  
  sample_v1_01 <- filter(sample_01, v_num==1)
  sample_v2_01 <- filter(sample_01, v_num==2)
  sample_v3_01 <- filter(sample_01, v_num==3)
  
  population_01 <- read.csv("/pine/scr/j/s/jsljr/HCHSSOL_AddHealth_WCs/population_3visits_June2021_missing.csv")
  
  population_v1_01 <- filter(population_01, v_num==1)
  population_v2_01 <- filter(population_01, v_num==2)
  population_v3_01 <- filter(population_01, v_num==3)
  
  # Visit indicators
  
  sample_v2_indicator_1 <- rename(sample_v2_01, v_num2=v_num)
  sample_v2_indicator_2 <- select(sample_v2_indicator_1, subid, v_num2)
  
  sample_v3_indicator_1 <- rename(sample_v3_01, v_num3=v_num)
  sample_v3_indicator_2 <- select(sample_v3_indicator_1, subid, v_num3)
  
  sample_v1_02 <- full_join(sample_v1_01, sample_v2_indicator_2, by = c("subid"))
  
  sample_v1_03 <- full_join(sample_v1_02, sample_v3_indicator_2, by = c("subid"))
  
  sample_v1_04 <- sample_v1_03 %>%
                  mutate(v2 =
                  case_when(v_num2==2 ~ 1,
                            is.na(v_num2) ~ 0))
  
  sample_v1_05 <- sample_v1_04 %>%
                  mutate(v3 =
                  case_when(v_num3==3 ~ 1,
                            is.na(v_num3) ~ 0))
  
  sample_v1_06 <- sample_v1_05 %>%
                  mutate(v3_reappear =
                  case_when(v2 == 0 & v3 == 1 ~ 1,
                           v2 == 1 & v3 == 1 ~ 0,
                           v2 == 0 & v3 == 0 ~ 0,
                           v2 == 1 & v3 == 0 ~ 0))
  
  # Here we create the variable v123, which is an indicator variable that
  # is 1 when a participant has attended all three visits and 0 otherwise.
  # Variables v_num2 and v_num3 are dropped.
  # Variable v_num is renamed to v1, so that it is consistent in naming
  # with visit 2 (v2) and visit 3 (v3) indicators.
  sample_v1_06 <- sample_v1_06 %>%
    mutate(v123 = ifelse(v_num==1 & v2==1 & v3==1, 1, 0)) %>%
    select(-v_num2, -v_num3, -x0, -x1, -x2, -x3, -x4,
           -x6, -x8, -x12, -x13, -x14, -x15, -x17, -x18,
           -y_bmi, -y_gfr, -y_bin_gfr_low, -y_bin_gfr_med,
           -y_bin_gfr_hi) %>%
    rename(v1 = v_num)
  
  ## Creating Multilevel Weights
  
  ### Level 3 (Block Group) weight components
  
  # level 3 v1 wc
  # level 3 visit 1 weight components
  # These are simply the W_bg weights already generated by the
  # V3_samp.R code
  
  # level 3 v2 wc
  # Level 3 Visit 2 weight components
  # Here we create summation_k W_bg_k based on the block group k.
  # The variable created is sum_w_bg_by_bg. This remains consistent
  # for all visits.
  sample_v1_07 <- sample_v1_06 %>%
    group_by(BGid) %>%
    mutate(sum_w_bg_by_bg = sum(W_bg))
  
  # Here we create a W_bg*V2_Q_k weight that takes into consideration
  # whether a block group was a part of visit 2.
  # The variable created is w_bg_v2_r.
  sample_v1_08 <- mutate(sample_v1_07, w_bg_v2_r = W_bg*v2)
  
  # Here we create summation_k w_bg_v2_r on the block group k
  # and whether the block group appears in v2.
  # The variable created is sum_w_bg_by_bg_v2.
  sample_v1_09 <- sample_v1_08 %>%
    group_by(BGid) %>%
    mutate(sum_w_bg_by_bg_v2 = sum(w_bg_v2_r))
  
  # Finally we create the phi_k (non-response) adjusted W_bg.
  # The variable created is W_bg_v2.
  sample_v1_10 <- mutate(sample_v1_09,
                         W_bg_v2 = 
                         W_bg*(sum_w_bg_by_bg)/(sum_w_bg_by_bg_v2))
  
  # Filter out part of the sample that did not attend visit 2.
  # sample_v2_wt_check <- filter(sample_v1_10, v2==1)
  
  # level 3 v3 wc 1
  # Level 3 Visit 3 Weight Components (a part of visit 1 and visit 3)
  
  # Here we create W_bg weight that takes into consideration
  # whether a block group was a part of visit 1 and visit 3.
  # The variable created is w_bg_v3_r_1.
  sample_v1_11 <- mutate(sample_v1_10, w_bg_v3_r_1 = W_bg*v3)
  
  # Here we create summation_k w_bg_v3_r_1 based on the block group k
  # and whether the block group appears in v1 and v3.
  # The variable created is sum_w_bg_by_bg_v3_1.
  sample_v1_12 <- sample_v1_11 %>%
    group_by(BGid) %>%
    mutate(sum_w_bg_by_bg_v3_1 = sum(w_bg_v3_r_1))
  
  # Finally we create the phi_k (non-response) adjusted W_bg.
  # The variable created is W_bg_v3_1.
  sample_v1_13 <- mutate(sample_v1_12,
                         W_bg_v3_1 =
                         W_bg*(sum_w_bg_by_bg)/(sum_w_bg_by_bg_v3_1))
  
  # level 3 v3 wc 2
  # Level 3 Visit 3 Weight Components (a part of visit 1, visit 2, and visit3)
  
  # Here we create a W_bg weight that takes into consideration
  # whether a block group was a part of visit 1, visit 2, and visit 3.
  # The variable created is w_bg_v3_r_2.
  sample_v1_14 <- mutate(sample_v1_13, w_bg_v3_r_2 = W_bg*v123)
  
  # Here we create summation_k w_bg_v3_r_2 based on the block group k
  # and whether the block group appears in v1, v2, & v3.
  # The variable created is sum_w_bg_by_bg_v3_2.
  sample_v1_15 <- sample_v1_14 %>%
    group_by(BGid) %>%
    mutate(sum_w_bg_by_bg_v3_2 = sum(w_bg_v3_r_2))
  
  sample_v1_16 <- mutate(sample_v1_15,
                         W_bg_v3_2 =
                         W_bg*(sum_w_bg_by_bg)/(sum_w_bg_by_bg_v3_2))
  
  # level 2 v1 wc
  # Level 2 Visit 1 Weight Components
  
  # Here we create summation_j W_j|k based on the block group k.
  # The variable created is sum_w_hh_by_bg. This remains consistent for
  # all visits.
  sample_v1_17 <- sample_v1_16 %>%
    group_by(BGid) %>%
    mutate(sum_w_hh_by_bg = sum(W_hh))
  
  # Here we create n_k which is the number of households in the block
  # group.
  popn_unq_hh <- population_v1_01[!duplicated(population_v1_01$hhid),]
  hh_count_by_bg <- aggregate(hhid ~ BGid, dat=popn_unq_hh, FUN=length)
  hh_count_by_bg <- hh_count_by_bg[order(hh_count_by_bg$BGid),]
  
  hh_count_by_bg <- rename(hh_count_by_bg, hh_count_by_bg = hhid)
  
  sample_v1_18 <- merge(sample_v1_17, hh_count_by_bg, by="BGid")
  
  # Here we create the final hh weight component for visit 1.
  sample_v1_19 <- mutate(sample_v1_18,
                         W_hh_v1 =
                         W_hh*(hh_count_by_bg)/(sum_w_hh_by_bg))
  
  # level 2 v2 wc
  # Level 2 Visit 2 Weight Components
  
  # Here we create a W_hh_v1*v2 weight that takes into consideration
  # whether a household group was a part of visit 2.
  # The variable created is w_hh_v2_r.
  sample_v1_20 <- mutate(sample_v1_19, w_hh_v2_r = W_hh_v1*v2)
  
  # Here we create summation_j w_hh_v2_r based on household group j
  # and whether the household appears in v2.
  # The variable created is sum_w_hh_by_bg_v2.
  sample_v1_21 <- sample_v1_20 %>%
    group_by(BGid) %>%
    mutate(sum_w_hh_by_bg_v2 = sum(w_hh_v2_r))
  
  # Finally we create the non-response adjusted W_hh_v1.
  # The variable created is W_hh_v2.
  sample_v1_22 <- mutate(sample_v1_21,
                         W_hh_v2 =
                         W_hh_v1*(sum_w_hh_by_bg)/(sum_w_hh_by_bg_v2))
  
  # level 2 v3 wc 1
  # Level 2 Visit 3 Weights (attend v1 and v3)
  
  # Here we create a W_hh_v1*v3 weight that takes into consideration
  # whether a household group was a part of visit 3.
  # The variable created is w_hh_v3_r_1.
  sample_v1_23 <- mutate(sample_v1_22, w_hh_v3_r_1 = W_hh_v1*v3)
  
  # Here we create summation_j w_hh_v3_r_1 based on household group j
  # and whether the household appears in v3.
  # The variable created is sum_w_hh_by_bg_v3_1.
  sample_v1_24 <- sample_v1_23 %>%
    group_by(BGid) %>%
    mutate(sum_w_hh_by_bg_v3_1 = sum(w_hh_v3_r_1))
  
  # Finally we create the non-response adjusted W_hh_v1.
  # The variable created is W_hh_v3_1.
  sample_v1_25 <- mutate(sample_v1_24,
                         W_hh_v3_1 =
                         W_hh_v1*(sum_w_hh_by_bg)/(sum_w_hh_by_bg_v3_1))
  
  # level 2 v3 wc 2
  # Level 2 Visit 3 Weights (attended v1, v2, and v3)
  
  # Here we create a W_hh_v1*v123 weight that takes into consideration
  # whether a household group was a part of visit 1, 2, and 3.
  # The variable created is w_hh_v3_r_2.
  sample_v1_26 <- mutate(sample_v1_25, w_hh_v3_r_2 = W_hh_v1*v123)
  
  # Here we create summation_j w_hh_v3_r_2 based on household group j
  # and whether the household appears in v1, v2, and v3.
  # The variable created is sum_w_hh_by_bg_v3_2.
  sample_v1_27 <- sample_v1_26 %>%
    group_by(BGid) %>%
    mutate(sum_w_hh_by_bg_v3_2 = sum(w_hh_v3_r_2))
  
  # Finally we create the non-response adjusted W_hh_v1.
  # The variable created is W_hh_v3_2.
  sample_v1_28 <- mutate(sample_v1_27,
                         W_hh_v3_2 =
                         W_hh_v1*(sum_w_hh_by_bg)/(sum_w_hh_by_bg_v3_2))
  
  # level 1 v1 wc
  # Level 1 visit 1 Weight Components
  
  # Here we create summation_i W_i|jk based on the household group j.
  # The variable created is sum_w_sub_by_hh. This will be used to #calculate all visit weights.
  sample_v1_29 <- sample_v1_28 %>%
    group_by(hhid) %>%
    mutate(sum_w_sub_by_hh = sum(W_sub))
  
  # Here we create n_j which is the number of subjects in the household.
  sub_count_by_hh <- aggregate(subid ~ BGid + hhid,
                               dat=population_v1_01, FUN=length)
  sub_count_by_hh <- sub_count_by_hh[order(sub_count_by_hh$BGid,
                                           sub_count_by_hh$subid),]
  
  sub_count_by_hh <- rename(sub_count_by_hh, sub_count_by_hh = subid)
  
  sample_v1_30 <- merge(sample_v1_29, sub_count_by_hh, by=c("BGid", "hhid"))
  
  # Here we create the final sub weight component for visit 1.
  sample_v1_31 <- mutate(sample_v1_30,
                         W_sub_v1 =
                         W_sub*((sub_count_by_hh)/(sum_w_sub_by_hh)))
  
  # level 1 v2 wc
  # Level 1 visit 2 weights
  
  # Here we create a W_sub_v1*v2 weight that takes into consideration
  # whether a household group was a part of visit 2.
  # The variable created is w_sub_v2_r.
  sample_v1_32 <- mutate(sample_v1_31, w_sub_v2_r = W_sub_v1*v2)
  
  # Here we create summation_i w_sub_v2_r based on subject i
  # and whether the subject appears in v2.
  # The variable created is sum_w_sub_by_hh_v2.
  sample_v1_33 <- sample_v1_32 %>%
    group_by(hhid) %>%
    mutate(sum_w_sub_by_hh_v2 = sum(w_sub_v2_r))
  
  # Finally we create the non-response adjusted W_sub_v1.
  # The variable created is W_sub_v2.
  
  sample_v1_34 = mutate(sample_v1_33,
                        W_sub_v2 =
                        W_sub_v1*(sum_w_sub_by_hh)/(sum_w_sub_by_hh_v2))
  
  # level 1 v3 wc 1
  # Level 1 visit 3 weights (attended v1 and v3)
  
  # Here we create a W_sub_v1*v3 weight that takes into consideration
  # whether a subject was a part of visit 3.
  # The variable created w_sub_v3_r_1.
  sample_v1_35 <- mutate(sample_v1_34, w_sub_v3_r_1 = W_sub_v1*v3)
  
  # Here we create summation_i w_sub_v3_r_1 based on subject i
  # and whether the subject appears in v3.
  # The variable created is sum_w_sub_by_hh_v3_1.
  sample_v1_36 <- sample_v1_35 %>%
    group_by(hhid) %>%
    mutate(sum_w_sub_by_hh_v3_1 = sum(w_sub_v3_r_1))
  
  # Finally we create the non-response adjusted W_sub_v1.
  # The variable created is W_sub_v3_1.
  sample_v1_37=mutate(sample_v1_36,
                      W_sub_v3_1 =
                      W_sub_v1*(sum_w_sub_by_hh)/(sum_w_sub_by_hh_v3_1))
  
  # level 1 v3 wc 2
  # Level 1 visit 3 weights (attended v1, v2, and v3)
  
  # Here we create a W_sub_v1*v123 weight that takes into consideration
  # whether a subject was a part of visit 1, 2, and 3.
  # The variable created w_sub_v3_r_2.
  sample_v1_38 <- mutate(sample_v1_37, w_sub_v3_r_2 = W_sub_v1*v123)
  
  # Here we create summation_i w_sub_v3_r_2 based on subject i
  # and whether the subject appears in v3.
  # The variable created is sum_w_sub_by_hh_v3_2.
  sample_v1_39 <- sample_v1_38 %>%
    group_by(hhid) %>%
    mutate(sum_w_sub_by_hh_v3_2 = sum(w_sub_v3_r_2))
  
  # Finally we create the non-response adjusted W_sub_v1.
  # The variable created is W_sub_v3_1.
  sample_v1_40 <- mutate(sample_v1_39,
                        W_sub_v3_2 =
                        W_sub_v1*(sum_w_sub_by_hh)/(sum_w_sub_by_hh_v3_2))
  
  sample_v1_41 <- sample_v1_40 %>% select(BGid, hhid, subid, W_bg, 
                                          W_hh, W_sub, W_bghhsub,
                                          W_bghh, W_hhsub, W_bg_v2,
                                          W_bg_v3_1, W_bg_v3_2,
                                          W_hh_v1, W_hh_v2, W_hh_v3_1,
                                          W_hh_v3_2,
                                          W_sub_v1, W_sub_v2, 
                                          W_sub_v3_1, W_sub_v3_2,
                                          dat_num)
  
  #sample_v1_42 <- sample_v1_41 %>% mutate(W_bghhsub_v1_1 =
  #                                          W_bg*W_hh_v1*W_sub_v1,
  #                                        W_bghhsub_v2_1 =
  #                                          W_bg_v2*W_hh_v2*W_sub_v2,
  #                                        W_bghhsub_v3_1 = 
  #                                          W_bg_v3_1*W_hh_v3_1*W_sub_v3_1,
  #                                        W_bghhsub_v3_2 =
  #                                          W_bg_v3_2*W_hh_v3_2*W_sub_v3_2)
  
  #sample_v1_43 <- sample_v1_42 %>% mutate(W_bghhsub_v1_norm = W_bghhsub_v1_1/mean(W_bghhsub_v1_1),
  #                                        W_bghhsub_v2_norm = W_bghhsub_v2_1/mean(W_bghhsub_v2_1),
  #                                        W_bghhsub_v3_norm_1 = W_bghhsub_v3_1/mean(W_bghhsub_v3_1),
  #                                       W_bghhsub_v3_norm_2 = W_bghhsub_v3_2/mean(W_bghhsub_v3_2))
  
  sample_v1_42 <- inner_join(sample_01, sample_v1_41)
  
  #sample_final <- sample_v1_44 %>%
  #  mutate(addhbwt_01 =
  #           case_when(v_num==1 ~ W_bghhsub_v1_norm,
  #                     v_num==2 ~ W_bghhsub_v2_norm,
  #                     v_num==3 ~ W_bghhsub_v3_norm_1),
  #         addhbwt_02 =
  #           case_when(v_num==1 ~ W_bghhsub_v1_norm,
  #                     v_num==2 ~ W_bghhsub_v2_norm,
  #                     v_num==3 ~ W_bghhsub_v3_norm_2))
  
  write.csv(sample_v1_42, paste0("/pine/scr/j/s/jsljr/HCHSSOL_AddHealth_WCs/Add_Samples/sample_",i,".csv"), row.names=FALSE)
}